[book]
authors = ["Rachit Nigam"]
language = "en"
multilingual = false
src = "docs"
title = "Filament"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js", "static/custom-highlight.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
