name = "xls"
path = "xls-gen.sh"
requires_out_file = true

[globals]
[modules.CompelxMultXLS]
name = "Butterfly"
parameters = ["Exp", "Mant"]
name_format = "Butterfly_Exp${Exp}_Mant${Mant}"
cli_format = "${NAME_FORMAT} butterfly.x ${OUT_FILE} ${Exp} ${Mant} Butterfly 10"
outputs.L = "pipeline_depth"
