name = "xls"
path = "./xls-gen.sh"
requires_out_file = true

[globals]
xls_path = "/home/xls"
src_path = "complex.x"
file_name = "complex.x"
stages = "4"

[modules.ComplexMult]
name = "ComplexMult"
parameters = ["Exp", "Mant"]
name_format = "ComplexMult_Exp${Exp}_Mant${Mant}"
cli_format = "${xls_path} ${NAME_FORMAT} ${src_path} ${OUT_FILE} ${Exp} ${Mant} ComplexMult ${stages}"
outputs.L = "pipeline_depth"
