name = "xls"
path = "xls-gen.sh"
requires_out_file = true

[globals]
mult_stages = "10"
add_stages = "10"

[modules.FPMultXLS]
name = "FPMultXLS"
parameters = ["Exp", "Mant"]
name_format = "FPMultXLS_Exp${Exp}_Mant${Mant}"
cli_format = "${NAME_FORMAT} float.x ${OUT_FILE} ${Exp} ${Mant} FPMultXLS ${mult_stages}"
outputs.L = "pipeline_depth"

[modules.FPAddXLS]
name = "FPAddXLS"
parameters = ["Exp", "Mant"]
name_format = "FPAddXLS_Exp${Exp}_Mant${Mant}"
cli_format = "${NAME_FORMAT} float.x ${OUT_FILE} ${Exp} ${Mant} FPAddXLS ${add_stages}"
outputs.L = "pipeline_depth"

[modules.FPSubXLS]
name = "FPSubXLS"
parameters = ["Exp", "Mant"]
name_format = "FPSubXLS_Exp${Exp}_Mant${Mant}"
cli_format = "${NAME_FORMAT} float.x ${OUT_FILE} ${Exp} ${Mant} FPSubXLS ${add_stages}"
outputs.L = "pipeline_depth"

[modules.FPNegXLS]
name = "FPNegXLS"
parameters = ["Exp", "Mant"]
name_format = "FPNegXLS_Exp${Exp}_Mant${Mant}"
cli_format = "${NAME_FORMAT} float.x ${OUT_FILE} ${Exp} ${Mant} FPNegXLS {add_stages}"
outputs.L = "pipeline_depth"


